### ISSUE TITLE
Swift 3 on master?

### ISSUE THREAD

**Issue by falkobuttler** [freeletics/FLTextView#18]
Do you have any plans to merge your Swift 3 branch into master and make it the stable version?

**Comment by falkobuttler** [comment]
Is this repo dead or will the swift 3 branch be merged back into master?

**Comment by PranKe01** [comment]
It's a shame that this pod isn't maintained as it should :|

**Comment by peter-roland-toth** [comment]
@falkobuttler , @PranKe01 : Sorry for the late reply. The Swift 3 branch has been merged into master and we created a new version (1.0.6) with it.

**Comment by falkobuttler** [comment]
Awesome, thanks!

**Comment by falkobuttler** [comment]
Reopening - I can't load this repo neither from `master`, tag `1.0.6` or with that version from CocoaPods directly.

`[!] Unable to find a specification for 'FLTextView'.`

**Comment by PranKe01** [comment]
Same here :(
https://github.com/freeletics/FLTextView/issues/20

**Comment by catalinaturlea** [comment]
@falkobuttler should be fixed now
