### ISSUE TITLE
Code review / check examples

### ISSUE THREAD

**Issue by danilobuerger** [freeletics/FLTextView#6]
@janweinkauff 
@Argent 
@jdcom 
@arsonic 
@calinadon

**Comment by janndriessen** [comment]
Text container inset looks weird. Don't know if it's just something in the examples. On iOS 7 it's definitely wrong. 
![img_0031](https://cloud.githubusercontent.com/assets/2104965/7115498/7994342a-e1e9-11e4-801d-45cfb07a91d9.PNG)

**Comment by janndriessen** [comment]
Functionality looked good :+1:

**Comment by danilobuerger** [comment]
Fixed this in ab6311f

**Comment by janndriessen** [comment]
Tested on devices iOS 7 + 8. Looks good to me.

**Comment by ghost** [comment]
Tested on iOS7/8. No issues found.

**Comment by ghost** [comment]
Regarding our control's description i would change it as follows:
"Compared to other similar libraries we **allow**(**enable**) the ability to grow (in height or content size) the area of UITextView depending on the size of the placeholder"

**Comment by danilobuerger** [comment]
Changed. I will close this as done now.
